# -*- coding: utf-8 -*-
"""week01_p01_hellow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jluGdKBRYQo2A0m7UemyXDbJGXn0ZkYI

# 這是第一支程式
"""

print("hello word")

# This is a simple program for beginners

# We can store numbers in variables
number1 = 10
number2 = 5

# We can perform calculations with variables
sum_of_numbers = number1 + number2

# We can print the result
print("The first number is:", number1)
print("The second number is:", number2)
print("The sum of the numbers is:", sum_of_numbers)

x = 10
y = 5

z = x + y
print(z)