print("      *      ")
print("     ***     ")
print("    *****    ")
print("   *******   ")
print("  *********  ")
print(" *********** ")
print("*************")
print("     |||     ")
print("     |||     ")
print("=== 聖誕快樂 ===")
